### ISSUE TITLE
2.0.1 causing typescript build failure

### ISSUE THREAD

**Issue by daguej** [googleapis/google-auth-library-nodejs#520]
Version 2.0.1 of this library has caused a build failure in a project where version 2.0.0 was previously working.

```
$ tsc
../node_modules/google-auth-library/build/src/auth/oauth2client.d.ts(291,55): error TS1039: Initializers are not allowed in ambient contexts.
```

The line in question is

```ts
protected static readonly GOOGLE_TOKEN_INFO_URL = "https://oauth2.googleapis.com/tokeninfo";
```

In 2.0.0 it was

```ts
protected static readonly GOOGLE_TOKEN_INFO_URL: string;
```
 
Likely related to #503 

Should this change have been semver major?

**Comment by JustinBeckwith** [comment]
Apologies for the trouble :/ what version of the TypeScript compiler and nodejs are you using?

**Comment by daguej** [comment]
TS 2.4.2 / node 8.12.0

**Comment by JustinBeckwith** [comment]
Could you try this with TypeScript 3.1.x?

**Comment by leofidus** [comment]
Same issue with Typescript 2.6.1 on Node 10. A build breaking with a semver patch update seems like a major oversight.

**Comment by JustinBeckwith** [comment]
Thanks folks! Can anyone verify this happens with TypeScript 3.x?

**Comment by ackushiw** [comment]
I can confirm that after updating typescript to 3.1.4 I don't get the build error.

**Comment by JustinBeckwith** [comment]
Thanks for the confirmation @ackushiw.  We can't really support older versions of TypeScript, so I'm going to close this one out.  If you run into this, please upgrade to the latest compiler :)

**Comment by yangzhu6263736** [comment]
I have the same problem  tsc 3.1.6 and node v10.7.0

**Comment by DNRN** [comment]
I also experince this issue with tsc 3.2.2 and node v8.9.4

**Comment by ifiokjr** [comment]
@JustinBeckwith This causes issues when creating [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) definition files which inherit from this library. At the moment it's not possible to set the minimum version to TS 3.2 and hence the ambient error keeps popping up.

See this closed PR as an example https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31145#issuecomment-447237745
